import { AsyncLocalStorage } from 'node:async_hooks';
import nodeConsole from 'node:console';
import { skipCSRFCheck } from '@auth/core';
import Credentials from '@auth/core/providers/credentials';
import { authHandler, initAuthConfig } from '@hono/auth-js';
import { handle as vercelNodeHandle } from '@hono/node-server/vercel';
import { Pool, neonConfig } from '@neondatabase/serverless';
import { hash, verify } from 'argon2';
import { Hono } from 'hono';
import { contextStorage } from 'hono/context-storage';
import { cors } from 'hono/cors';
import { requestId } from 'hono/request-id';
import { createMiddleware } from 'hono/factory';
import { createRequestHandler } from 'react-router';
import { serializeError } from 'serialize-error';
import ws from 'ws';

// React Router server build (generated by `react-router build`)
import * as reactRouterBuild from '../apps/web/build/server/assets/server-build.js';

// API route modules (source)
import * as gamesRoute from '../apps/web/src/app/api/games/route.js';
import * as gameRoute from '../apps/web/src/app/api/games/[id]/route.js';
import * as joinRoute from '../apps/web/src/app/api/games/[id]/join/route.js';
import * as authTokenRoute from '../apps/web/src/app/api/auth/token/route.js';
import * as expoWebSuccessRoute from '../apps/web/src/app/api/auth/expo-web-success/route.js';
import * as ssrTestRoute from '../apps/web/src/app/api/__create/ssr-test/route.js';

neonConfig.webSocketConstructor = ws;

const als = new AsyncLocalStorage();

for (const method of ['log', 'info', 'warn', 'error', 'debug']) {
  const original = nodeConsole[method].bind(console);
  console[method] = (...args) => {
    const requestId = als.getStore()?.requestId;
    if (requestId) original(`[traceId:${requestId}]`, ...args);
    else original(...args);
  };
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

// Minimal copy of the Neon adapter (reuse your existing one)
// Importing your adapter directly keeps behavior identical.
import NeonAdapter from '../apps/web/__create/adapter.ts';
const adapter = NeonAdapter(pool);

const app = new Hono();

app.use('*', requestId());
app.use('*', (c, next) => {
  const rid = c.get('requestId');
  return als.run({ requestId: rid }, () => next());
});
app.use(contextStorage());

app.onError((err, c) => {
  if (c.req.method !== 'GET') {
    return c.json(
      { error: 'An error occurred in your app', details: serializeError(err) },
      500
    );
  }
  // Don’t leak details in HTML in production; return a simple response.
  return c.html('An error occurred', 500);
});

if (process.env.CORS_ORIGINS) {
  app.use(
    '/*',
    cors({
      origin: process.env.CORS_ORIGINS.split(',').map((o) => o.trim()),
    })
  );
}

if (process.env.AUTH_SECRET) {
  app.use(
    '*',
    initAuthConfig((c) => ({
      secret: c.env.AUTH_SECRET,
      pages: { signIn: '/account/signin', signOut: '/account/logout' },
      skipCSRFCheck,
      session: { strategy: 'jwt' },
      callbacks: {
        session({ session, token }) {
          if (token.sub) session.user.id = token.sub;
          return session;
        },
      },
      cookies: {
        csrfToken: { options: { secure: true, sameSite: 'none' } },
        sessionToken: { options: { secure: true, sameSite: 'none' } },
        callbackUrl: { options: { secure: true, sameSite: 'none' } },
      },
      providers: [
        Credentials({
          id: 'credentials-signin',
          name: 'Credentials Sign in',
          credentials: { email: { label: 'Email', type: 'email' }, password: { label: 'Password', type: 'password' } },
          authorize: async (credentials) => {
            const { email, password } = credentials ?? {};
            if (!email || !password) return null;
            if (typeof email !== 'string' || typeof password !== 'string') return null;

            const user = await adapter.getUserByEmail(email);
            if (!user) return null;
            const matchingAccount = user.accounts.find((a) => a.provider === 'credentials');
            const accountPassword = matchingAccount?.password;
            if (!accountPassword) return null;
            if (!(await verify(accountPassword, password))) return null;
            return user;
          },
        }),
        Credentials({
          id: 'credentials-signup',
          name: 'Credentials Sign up',
          credentials: { email: { label: 'Email', type: 'email' }, password: { label: 'Password', type: 'password' } },
          authorize: async (credentials) => {
            const { email, password } = credentials ?? {};
            if (!email || !password) return null;
            if (typeof email !== 'string' || typeof password !== 'string') return null;

            const user = await adapter.getUserByEmail(email);
            if (user) return null;

            const newUser = await adapter.createUser({
              id: crypto.randomUUID(),
              emailVerified: null,
              email,
            });
            await adapter.linkAccount({
              extraData: { password: await hash(password) },
              type: 'credentials',
              userId: newUser.id,
              providerAccountId: newUser.id,
              provider: 'credentials',
            });
            return newUser;
          },
        }),
      ],
    }))
  );
}

// --- API routing (explicit mapping for Vercel) ---
function bindRoute(module, pathPattern) {
  const methods = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'];
  for (const method of methods) {
    if (!module[method]) continue;
    const honoMethod = method.toLowerCase();
    app[honoMethod](pathPattern, async (c) => {
      const params = c.req.param();
      return await module[method](c.req.raw, { params });
    });
  }
}

bindRoute(gamesRoute, '/api/games');
bindRoute(gameRoute, '/api/games/:id');
bindRoute(joinRoute, '/api/games/:id/join');
bindRoute(authTokenRoute, '/api/auth/token');
bindRoute(expoWebSuccessRoute, '/api/auth/expo-web-success');
bindRoute(ssrTestRoute, '/api/__create/ssr-test');

app.use('/api/auth/*', async (c, next) => {
  // Keep Auth.js handler compatibility for other actions
  return authHandler()(c, next);
});

// --- React Router SSR ---
app.use('*', createMiddleware(async (c) => {
  const mode = process.env.NODE_ENV === 'production' ? 'production' : 'development';
  const requestHandler = createRequestHandler(reactRouterBuild, mode);
  return requestHandler(c.req.raw);
}));

export default vercelNodeHandle(app);

